drop TABLE CC_REPORT_CATALOG ;
CREATE TABLE CC_REPORT_CATALOG (
    REPORT_ID NUMBER NOT NULL 
    , label VARCHAR2(1024) 
    , COMMON_NAME VARCHAR2(1024) 
    , DISPLAY_NAME VARCHAR2(1024) 
    , report_description VARCHAR2(1024) 
    , LAYOUT_OPTION VARCHAR2(1024) 
    , HANDLER_OBJECT_NAME VARCHAR2(1024) 
    , STORED_PROCEDURED_NAME VARCHAR2(1024) 
    , STATUS VARCHAR2(32) 
    , LAST_MODIFICATION_DATE DATE 
    , LAST_MODIFICATION_BY VARCHAR2(1024) 
    , LAYOUT_POSITION NUMBER 
    , CONSTRAINT CC_REPORT_CATALOG_PK PRIMARY KEY ( REPORT_ID  ) ENABLE 
);